"""ranked debates

Revision ID: 7da268de2e9c
Revises: 9dfc85b08c19
Create Date: 2026-09-23 23:05:40.625843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da268de2e9c'
down_revision: Union[str, None] = '9dfc85b08c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('ranked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'ranked')
    # ### end Alembic commands ###
