"""baseline schema

Revision ID: 9dfc85b08c19
Revises: 
Create Date: 2026-09-23 22:22:25.115124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dfc85b08c19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_verifiable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cognitive_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('archetype', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('elo_rating', sa.Float(), nullable=False),
    sa.Column('debates_judged', sa.Integer(), nullable=False),
    sa.Column('debates_rated_in', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('predicted_belief', sa.Float(), nullable=False),
    sa.Column('actual_outcome', sa.Float(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cognitive_agents.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agent_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('final_belief_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('argument_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unknown_unknowns', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('synthesis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debate_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('belief_score', sa.Float(), nullable=False),
    sa.Column('probability_true', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=False),
    sa.Column('confidence_high', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('key_evidence', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('cruxes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cognitive_agents.id'], ),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arguments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debate_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('source_agent_id', sa.UUID(), nullable=False),
    sa.Column('target_argument_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.ForeignKeyConstraint(['source_agent_id'], ['cognitive_agents.id'], ),
    sa.ForeignKeyConstraint(['target_argument_id'], ['arguments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jury_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debate_id', sa.UUID(), nullable=False),
    sa.Column('judge_agent_id', sa.UUID(), nullable=False),
    sa.Column('subject_agent_id', sa.UUID(), nullable=False),
    sa.Column('method_fidelity', sa.Integer(), nullable=False),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('crux_quality', sa.Integer(), nullable=False),
    sa.Column('responsiveness', sa.Integer(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.ForeignKeyConstraint(['judge_agent_id'], ['cognitive_agents.id'], ),
    sa.ForeignKeyConstraint(['subject_agent_id'], ['cognitive_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jury_ratings')
    op.drop_table('arguments')
    op.drop_table('agent_positions')
    op.drop_table('debates')
    op.drop_table('calibration_records')
    op.drop_table('cognitive_agents')
    op.drop_table('claims')
    op.drop_table('users')
    # ### end Alembic commands ###
